# -*- coding: utf-8 -*-
"""Project 5 Capstone 4521.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118Izu9llkbnnoWT1-fmWWlPeQElV8ulx
"""

import pandas as pd
import numpy as np
import os
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Subset
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Subset, TensorDataset, Dataset
from transformers import AutoImageProcessor, AutoModel
from tqdm.auto import tqdm
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)


# Download latest version
path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")

print("Path to dataset files:", path)

"""Problem: Can we train a model to predict if someone has a certain brain tumor using MRI images.

## Section 1

The problem I’m trying to solve is whether I can train a model to detect certain brain tumors on an MRI machine. I will do this by going over each image, and the model will either predict whether the image is a tumor and describe its type, or that it is not a brain tumor. The dataset contains 4 classes that contain 400 images, making the model have a fair and unbiased evaluation when being trained. The 4 classes are named glioma, pituitary, meningioma, and notumor. The dataset is also a multi-class classification problem. The data also contains 512X512-pixel images and 7200 human brain MRI images categorized into four classes. This is an interesting problem because if this model is successfully able to predict brain tumors for my project, then it could also be used in real life to find brain tumors in patients, so that doctors don’t have to manually look for them using the MRI images. So the medical world will benefit heavily if machine learning models can predict brain tumors very accurately. My dataset contains 5,600 training data images and 1,600 testing data images. I further divided the training set into an 80/20 train/test split. There are no class imbalances in the dataset since each class has an equal number of images being used. However, one limitation is that the dataset doesn’t include the ages of the brains scanned or the gender, so we have less data on those metrics. Another limitation is that most of the images in the database are black and white MRI images and could fail on different MRI scans that are in color, so the model might be less accurate on those MRI images. Here is the link: https://www.kaggle.com/datasets/masoudnickparvar/brain-tumor-mri-dataset.

## Section 2
"""

from pathlib import Path
from PIL import Image

dataset_p = Path(path)
train = dataset_p/"Training"
test = dataset_p/"Testing"
class_label = sorted([i.name for i in train.iterdir() if i.is_dir()])
print(f"Classes:{class_label}")
print(f"Class amount:{len(class_label)}")
class_idx = {j: i for i, j in enumerate(class_label)}

def load_image_dataset(split_dir):
  data = []
  targets = []
  for folder in sorted(split_dir.iterdir()):
    if not folder.is_dir():
      continue
    for path_img in folder.glob("*"):
      if path_img.suffix.lower() in ['.jpg', '.jpeg', '.png']:
        data.append(path_img)
        targets.append(class_idx[folder.name])
  return data, targets

train_paths, train_labels = load_image_dataset(train)
test_paths, test_labels = load_image_dataset(test)
print(f"Train images: {len(train_paths)}")
print(f"Test images: {len(test_paths)}")
print(f"Class Distribution: {pd.Series(train_labels).value_counts()}")

class FolderDataset(Dataset):
  def __init__(self,data, targets, classes):
      self.data = np.array(data)
      self.targets = targets
      self.classes = classes

  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx):
    img = Image.open(self.data[idx]).convert("RGB")
    return img, self.targets[idx]

train_full = FolderDataset(train_paths, train_labels, class_label)
test_dataset = FolderDataset(test_paths, test_labels, class_label)
all_idx = np.arange(len(train_full))
all_labels = np.array(train_full.targets)
train_idx, value_idx = train_test_split(all_idx, test_size=0.2, random_state=42, stratify= all_labels)
dataset_tr = Subset(train_full, train_idx.tolist())
dataset_val = Subset(train_full, value_idx.tolist())
class_len = len(class_label)
print(f"Train:{len(dataset_tr)}, Val:{len(dataset_val)}, Test:{len(test_dataset)}\n")
print(f"Classes: {class_label}")

import random
np.random.seed(40)
torch.manual_seed(40)
test_labels = np.array(test_dataset.targets)
# Extract ground-truth labels for train and validation subsets
train_labels = all_labels[train_idx]
val_labels = all_labels[value_idx]

def plot_distribution(labels, title):
    counts = pd.Series(labels).value_counts().sort_index()
    df_dist = pd.DataFrame({
        "class": [class_label[i] for i in counts.index],
        "count": counts.values,
        "pct": (counts.values / counts.values.sum()) * 100,
    })
    display(df_dist)
    plt.figure(figsize=(10, 4))
    sns.barplot(data=df_dist, x="class", y="count", hue="class", legend=False)
    plt.xticks(rotation=35)
    plt.title(title)
    plt.tight_layout()
    plt.show()


print("Train distribution")
plot_distribution(train_labels, "Train class distribution")
print("Validation distribution")
plot_distribution(val_labels, "Validation class distribution")
print("Test distribution")
plot_distribution(test_labels, "Test class distribution")


fig, axes = plt.subplots(2, 5, figsize=(12, 5))
for i, ax in enumerate(axes.flatten()):
    img, label = train_full[random.randint(0, len(train_full) - 1)]
    ax.imshow(img)
    ax.set_title(class_label[label])
    ax.axis("off")
plt.suptitle(f"MRI Samples of Brains")
plt.tight_layout()
plt.show()

# Load frozen DINOv2 backbone for embedding extraction (no finetuning here).

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
embed_batch = 64
cache_dir = "./cache/brain_tumor"

os.makedirs(cache_dir,exist_ok = True)
dino_processor = AutoImageProcessor.from_pretrained("facebook/dinov2-small", use_fast=True)
dino_model = AutoModel.from_pretrained("facebook/dinov2-small").to(DEVICE)
dino_model.eval()


def collate_pil(batch):
    images, labels = zip(*batch)
    return list(images), torch.tensor(labels, dtype=torch.long)


def extract_embeddings(dataset_obj, split_name):
    cache_x = Path(cache_dir) / f"{split_name}_embeddings.pt"
    cache_y = Path(cache_dir) / f"{split_name}_labels.pt"

    if cache_x.exists() and cache_y.exists():
        print(f"Loading cached embeddings for {split_name}")
        return torch.load(cache_x, map_location="cpu"), torch.load(cache_y, map_location="cpu")

    loader = DataLoader(
        dataset_obj,
        batch_size=embed_batch,
        shuffle=False,
        num_workers=0,
        collate_fn=collate_pil,
    )

    all_embs = []
    all_labs = []

    print(f"Extracting embeddings for {split_name} in batches of {embed_batch} ...")
    with torch.no_grad():
        for images, labels in tqdm(loader, desc=f"Embeddings [{split_name}]"):
            # Convert image batch into model inputs and move tensors to selected device.
            inputs = dino_processor(images=images, return_tensors="pt").to(DEVICE)

            outputs = dino_model(**inputs)

            # Use [CLS] token embedding as the global image representation.
            embs = outputs.last_hidden_state[:, 0, :].cpu()
            all_embs.append(embs)
            all_labs.append(labels)

    X = torch.cat(all_embs, dim=0)
    y = torch.cat(all_labs, dim=0)
    torch.save(X, cache_x)
    torch.save(y, cache_y)
    print(f"Saved {split_name} embeddings: {tuple(X.shape)}")
    return X, y

X_train, y_train = extract_embeddings(dataset_tr, "train")
X_val, y_val = extract_embeddings(dataset_val, "val")
X_test, y_test = extract_embeddings(test_dataset, "test")

# We can extract the embedding dimensionality for the feature size per image
print(f"Embedding dimension: {X_train.shape[1]}")

np.random.seed(40)
torch.manual_seed(40)
torch.cuda.manual_seed(40)
torch.backends.cudnn.deterministic = True
class MLPClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dims, num_classes):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden_dims:
            # MLP head: Linear -> ReLU -> Dropout block repeated per hidden layer
            layers.extend([nn.Linear(prev, h), nn.ReLU(), nn.Dropout(0.2)])
            prev = h
        layers.append(nn.Linear(prev, num_classes))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


def make_loader(X, y, batch_size, shuffle=False):
    ds = TensorDataset(X.float(), y.long())
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle)


train_loader = make_loader(X_train, y_train, 256, shuffle=True)
val_loader = make_loader(X_val, y_val, 256, shuffle=False)
test_loader = make_loader(X_test, y_test, 256, shuffle=False)
mlp_epoch = 28
mlp_batch_size = 256
lr = 0.001
num_classes = len(class_label)
mlp = MLPClassifier(
    input_dim=X_train.shape[1],
    hidden_dims=[512,128],
    num_classes= num_classes,
).to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(mlp.parameters(), lr=lr)

print("Training config:")
print(f"hidden_dims={[512, 128]}, lr={lr}, epochs={mlp_epoch}, batch={mlp_batch_size}")
print(f"early_stopping_patience={6}")

history = {"train_loss": [], "val_loss": [], "val_acc": []}
best_val_acc = -1.0
best_path = Path(cache_dir) / "best_mlp.pt"
patience_left = 6

epoch_iter = tqdm(range(1, mlp_epoch + 1), desc="MLP epochs", unit="epoch")
for epoch in epoch_iter:
    mlp.train()
    train_loss = 0.0

    for xb, yb in train_loader:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optimizer.zero_grad()
        logits = mlp(xb)
        loss = criterion(logits, yb)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * xb.size(0)

    train_loss /= len(train_loader.dataset)

    mlp.eval()
    val_loss = 0.0
    val_preds = []
    val_true = []

    with torch.no_grad():
        for xb, yb in val_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            logits = mlp(xb)
            loss = criterion(logits, yb)
            val_loss += loss.item() * xb.size(0)
            val_preds.append(logits.argmax(dim=1).cpu().numpy())
            val_true.append(yb.cpu().numpy())

    val_loss /= len(val_loader.dataset)
    val_preds = np.concatenate(val_preds)
    val_true = np.concatenate(val_true)
    val_acc = accuracy_score(val_true, val_preds)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)

    improved = val_acc > best_val_acc
    if improved:
        best_val_acc = val_acc
        torch.save(mlp.state_dict(), best_path)
        patience_left = 6
    else:
        patience_left -= 1

    epoch_iter.set_postfix(
        train_loss=f"{train_loss:.4f}",
        val_loss=f"{val_loss:.4f}",
        val_acc=f"{val_acc:.4f}",
        best=f"{best_val_acc:.4f}",
        patience=patience_left,
    )

    # Stop when validation accuracy no longer improves for several epochs
    if patience_left == 0:
        print("Early stopping triggered.")
        break

print(f"Best validation accuracy: {best_val_acc:.4f}")

mlp.load_state_dict(torch.load(best_path, map_location=DEVICE))
mlp.eval()

all_logits = []
all_true = []
with torch.no_grad():
    for xb, yb in test_loader:
        xb = xb.to(DEVICE)
        logits = mlp(xb).cpu()
        all_logits.append(logits)
        all_true.append(yb)

test_logits = torch.cat(all_logits)
test_true = torch.cat(all_true).numpy()
test_probs = torch.softmax(test_logits, dim=1).numpy()
test_pred = test_probs.argmax(axis=1)

mlp_metrics = {
    "accuracy": accuracy_score(test_true, test_pred),
    "macro_f1": f1_score(test_true, test_pred, average="macro"),
}
print("MLP Test Metrics:", mlp_metrics)
epochs = np.arange(1, len(history["train_loss"]) + 1)
plt.figure(figsize=(8, 4))
plt.plot(epochs, history["train_loss"], label="Train loss")
plt.plot(epochs, history["val_loss"], label="Val loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("MLP loss over time")
plt.legend()
plt.tight_layout()
plt.show()

def evaluate_predictions(y_true, y_pred, names, title):
    acc = accuracy_score(y_true, y_pred)
    macro = f1_score(y_true, y_pred, average="macro")
    print(f"{title} accuracy: {acc:.4f}")
    print(f"{title} macro-F1: {macro:.4f}")
    print(classification_report(y_true, y_pred, target_names=names))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=names, yticklabels=names)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title(f"{title} confusion matrix")
    plt.tight_layout()
    plt.show()
    return cm


mlp_cm = evaluate_predictions(test_true, test_pred, class_label, "DINOv2+MLP")


def top_confusion_pairs(cm, names, k=5):
    pairs = []
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            if i != j and cm[i, j] > 0:
                pairs.append((cm[i, j], i, j))
    pairs.sort(reverse=True)
    return [(count, names[i], names[j]) for count, i, j in pairs[:k]]


print("Top confusion pairs (MLP):")
for count, t, p in top_confusion_pairs(mlp_cm, class_label, k=8):
    print(f"{t:>10} -> {p:<10}: {count}")

def collect_misclassified_examples(dataset_obj, y_true, y_pred, probs, max_examples=12):
    wrong_idx = np.where(y_true != y_pred)[0]
    records = []
    for i in wrong_idx:
        records.append(
            {
                "idx": int(i),
                "true": int(y_true[i]),
                "pred": int(y_pred[i]),
                "confidence": float(probs[i, y_pred[i]]),
            }
        )
    records.sort(key=lambda x: x["confidence"], reverse=True)
    return records[:max_examples]

mlp_mis_examples = collect_misclassified_examples(test_dataset, test_true, test_pred, test_probs, max_examples=15)
print(f"Collected {len(mlp_mis_examples)} misclassified examples (MLP).")

def show_examples(dataset_obj, examples, names, title, ncols=5):
    if not examples:
        print("No examples to show.")
        return
    n = len(examples)
    nrows = int(np.ceil(n / ncols))
    plt.figure(figsize=(3.5 * ncols, 3.5 * nrows))
    for k, ex in enumerate(examples, start=1):
        img, _ = dataset_obj[ex["idx"]]
        plt.subplot(nrows, ncols, k)
        plt.imshow(img)
        plt.title(
            f"True: {names[ex['true']]}\nPred: {names[ex['pred']]}\nConf: {ex['confidence']:.2f}",
            fontsize=14,
        )
        plt.axis("off")
    plt.suptitle(title, fontsize=16)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()


show_examples(test_dataset, mlp_mis_examples[:10], class_label, "MLP common misclassifications")

"""## Section 3"""

# !pip install -q openai

# from openai import OpenAI
# import base64
# import io
# import re

# client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY", "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"))

# gpt_prompt = (f"I want you to classify Brain Tumor MRI dataset images. Can you please choose one label from the classes:{', '.join(class_label)}."
#               "return only the label word.")

# rng = np.random.default_rng(seed=40)
# subset_n = 100

# if subset_n > len(test_dataset):
#   subset_n = len(test_dataset)


# qwen_indices = rng.choice(len(test_dataset), size=subset_n, replace=False)

# def parse_label(text: str):
#     cleaned = text.strip().lower()
#     for lbl in class_label:
#         if re.search(rf"\b{re.escape(lbl.lower())}\b", cleaned):
#             return lbl
#     return "unknown"


# def endcode_image(image):
#   if torch.is_tensor(image):
#     from torchvision import transforms
#     image = transforms.ToPILImage()(image)

#   buffer = io.BytesIO();
#   image.save(buffer, format ="JPEG")
#   return base64.b64encode(buffer.getvalue()).decode('utf-8')

# records = []

# for i in tqdm(qwen_indices, desc="ChatGPT inference"):
#   image, t_label_idx = test_dataset[int(i)]
#   base64_image = endcode_image(image)
#   try:
#     resp = client.chat.completions.create(
#         model = "gpt-4o-mini",
#         messages = [
#                {"role": "user",
#                 "content": [
#                     {"type": "text", "text": gpt_prompt},
#                     {"type":"image_url",
#                     "image_url" : {"url":f"data:image/jpeg;base64,{base64_image}"}
#                      },
#                 ],

#             },

#         ],
#         max_tokens = 10,
#         temperature = 0,
#     )
#     out = resp.choices[0].message.content.strip()
#     parse = parse_label(out)
#   except Exception as e:
#     out, parse = f"ERROR: {e}", "unknown"
#   records.append({
#       "idx": int(i),
#       "true_label": class_label[int(t_label_idx)],
#       "pred_label": parse
#   })

# gpt_df = pd.DataFrame(records)

# gpt_df = pd.DataFrame(records)
# display(gpt_df.head())

y_true_q = gpt_df["true_label"].values
y_pred_q = gpt_df["pred_label"].values

# Calculate unknown/parse failure count
unknown_mask = y_pred_q == "unknown"
num_unknowns = np.sum(unknown_mask)
parse_failure_rate = num_unknowns / len(y_pred_q)

print(f"Total ChatGPT Predictions: {len(y_pred_q)}")
print(f"Unknown/Parse Failures: {num_unknowns} ({parse_failure_rate:.2%})")

# Filter out unknowns for the confusion matrix and report
y_true_filtered = y_true_q[~unknown_mask]
y_pred_filtered = y_pred_q[~unknown_mask]
valid_indices = gpt_df["idx"].values[~unknown_mask]

# Map back to indices for the original 10 classes
label_to_idx_10 = {c: i for i, c in enumerate(class_label)}
y_true_idx = np.array([label_to_idx_10[x] for x in y_true_filtered])
y_pred_idx = np.array([label_to_idx_10[x] for x in y_pred_filtered])

# Store metrics for comparison table
gpt_metrics = {
    "accuracy": accuracy_score(y_true_q, y_pred_q),
    "macro_f1": f1_score(y_true_filtered, y_pred_filtered, average="macro"),
    "parse_failure_rate": parse_failure_rate,
    "avg_latency_sec": np.nan
}

print(f"\nEvaluation on successful parses ({len(y_true_filtered)} samples):")
gpt_cm = evaluate_predictions(y_true_idx, y_pred_idx, class_label, "gpt-4o-mini")

print("\nTop confusion pairs (GPT):")
for count, t, p in top_confusion_pairs(gpt_cm, class_label, k=8):
    print(f"{t:>10} -> {p:<10}: {count}")

# Collect and show misclassified examples
gpt_wrong_mask = y_true_filtered != y_pred_filtered
wrong_indices = valid_indices[gpt_wrong_mask]
wrong_true = y_true_idx[gpt_wrong_mask]
wrong_pred = y_pred_idx[gpt_wrong_mask]

qwen_examples = []
for i in range(len(wrong_indices)):
    qwen_examples.append({
        "idx": int(wrong_indices[i]),
        "true": int(wrong_true[i]),
        "pred": int(wrong_pred[i]),
        "confidence": 0.0
    })

show_examples(test_dataset, qwen_examples[:10], class_label, "(gpt-4o-mini) misclassifications")

"""## Section 4"""

comparison_rows = [
    {
        "method": "DINOv2 embeddings + MLP",
        "eval_set": f"Full Tumor MRI dataset test set",
        "accuracy": mlp_metrics["accuracy"],
        "macro_f1": mlp_metrics["macro_f1"],
        "avg_latency_sec": np.nan,
        "parse_failure_rate": np.nan,
    }
]

if gpt_metrics is not None:
    comparison_rows.append(
        {
            "method": "gpt-4o-mini prompt",
            "eval_set": f"Fixed test subset (n={len(gpt_df)})",
            "accuracy": gpt_metrics["accuracy"],
            "macro_f1": gpt_metrics["macro_f1"],
            "avg_latency_sec": gpt_metrics["avg_latency_sec"],
            "parse_failure_rate": gpt_metrics["parse_failure_rate"],
        }
    )

comparison_df = pd.DataFrame(comparison_rows)
display(comparison_df)

melt_df = comparison_df.melt(
    id_vars=["method"],
    value_vars=["accuracy", "macro_f1"],
    var_name="metric",
    value_name="value",
)

plt.figure(figsize=(8, 4))
sns.barplot(data=melt_df, x="metric", y="value", hue="method")
plt.ylim(0, 1.0)
plt.legend(loc='lower right')
plt.title("Embedding+MLP vs gpt-4o-mini")
plt.tight_layout()
plt.show()